insert overwrite table DATABASENAME1.TABLENAME1
select
1 as COLUMNNAME1
,coalesce(CHRTL.COLUMNNAME2, 'N/A') as COLUMNNAME3
,coalesce(CHRTL.COLUMNNAME4, 'N/A') as COLUMNNAME2
,coalesce(LHRTLSHP.COLUMNNAME5, 'N/A') as COLUMNNAME5
,coalesce(COLUMNNAME6(LHRTLSHP.COLUMNNAME7,COLUMNNAME8,COLUMNNAME9), 'N/A') as COLUMNNAME7
,coalesce(LHRTLSHP.COLUMNNAME10, 'N/A') as COLUMNNAME10
,coalesce(LHRTLSHP.COLUMNNAME11, 'N/A') as COLUMNNAME11
,coalesce(LHRTLSHP.COLUMNNAME12, 'N/A') as COLUMNNAME12
,coalesce(LHRTLSHP.COLUMNNAME13, 'N/A') as COLUMNNAME13
,coalesce(LHRTLSHP.COLUMNNAME14, 'N/A') as COLUMNNAME14
,coalesce(LHRTLSHP.COLUMNNAME15, 'N/A') as COLUMNNAME15
,coalesce(LHRTLSHP.COLUMNNAME16, 'N/A') as COLUMNNAME16
,coalesce(LHRTLSHP.COLUMNNAME17, 'N/A') as COLUMNNAME17
,coalesce(LHRTLSHP.COLUMNNAME18, 'N/A') as COLUMNNAME18
,coalesce(LHRTLSHP.COLUMNNAME19 ,Date_cmp(days_Add(AddDate(now(),2),4),AddDate(days_Add(AddDate(now(),2),6),2))) as COLUMNNAME19
,coalesce(LHRTLSHP.COLUMNNAME23, 'N/A') as COLUMNNAME23
,coalesce(LHRTLSHP.COLUMNNAME24, '9999-12-31') as COLUMNNAME24
,coalesce(LHRTLSHP.COLUMNNAME25 ,'9999-12-31') as COLUMNNAME25
,coalesce(LHRTLSHP.COLUMNNAME26 ,'00 : 00 : 00') as  COLUMNNAME26
,coalesce(LHRTLSHP.COLUMNNAME27, 'N/A') as COLUMNNAME27
,coalesce(LHRTLSHP.COLUMNNAME28, 'N/A') as COLUMNNAME28
,coalesce(LHRTLSHP.COLUMNNAME29, 'N/A') as COLUMNNAME29
,coalesce(LHRTLSHP.COLUMNNAME30, 'N/A') as COLUMNNAME30
,coalesce(LHRTLSHP.COLUMNNAME31, 'N/A') as COLUMNNAME31
,coalesce(LHRTLSHP.COLUMNNAME32, 'N/A') as COLUMNNAME32
,coalesce(LHRTLSHP.COLUMNNAME33 ,'9999-12-31') as COLUMNNAME33
,coalesce(LHRTLSHP.COLUMNNAME34 ,MILLISECONDS_sub(from_timeStamp(days_Add(AddDate(COLUMNNAME36,2),4),'yyyy-MM-dd HH : mm : ss'),3)) as COLUMNNAME34
,coalesce(LHRTLSHP.COLUMNNAME37, 'N/A') as COLUMNNAME37
,coalesce(THRTLSHP.COLUMNNAME38, 'N/A') as COLUMNNAME38
,coalesce(THRTLSHP.COLUMNNAME39, 'N/A') as COLUMNNAME39
,coalesce(THRTLSHP.COLUMNNAME40, 'N/A') as COLUMNNAME40
,coalesce(THRTLSHP.COLUMNNAME41  ,'9999-12-31') as COLUMNNAME41
,coalesce(THRTLSHP.COLUMNNAME42  ,'00 : 00 : 00') as COLUMNNAME42
,coalesce(THRTLSHP.COLUMNNAME43  ,0) as COLUMNNAME43
,coalesce(THRTLSHP.COLUMNNAME44, 'N/A') as COLUMNNAME44
,coalesce(THRTLSHP.COLUMNNAME11, 'N/A') as COLUMNNAME45
,coalesce(THRTLSHP.COLUMNNAME23, 'N/A') as COLUMNNAME46
,coalesce(THRTLSHP.COLUMNNAME47, 'N/A') as COLUMNNAME47
,coalesce(THRTLSHP.COLUMNNAME48 ,0) as COLUMNNAME48
,coalesce(THRTLSHP.COLUMNNAME49, 'N/A') as COLUMNNAME49
,coalesce(THRTLSHP.COLUMNNAME50  ,0) as COLUMNNAME50
,coalesce(THRTLSHP.COLUMNNAME51  ,0) as COLUMNNAME51
,coalesce(THRTLSHP.COLUMNNAME52, 'N/A') as COLUMNNAME52
,coalesce(THRTLSHP.COLUMNNAME53, 'N/A') as COLUMNNAME53
,coalesce(THRTLSHP.COLUMNNAME54, 'N/A') as COLUMNNAME54
,coalesce(THRTLSHP.COLUMNNAME31,'9999-12-31') as COLUMNNAME55
,coalesce(THRTLSHP.COLUMNNAME32 ,'00 : 00 : 00') as COLUMNNAME56
,coalesce(THRTLSHP.COLUMNNAME33  ,'9999-12-31') as COLUMNNAME57
,coalesce(THRTLSHP.COLUMNNAME34 ,'00 : 00 : 00') as COLUMNNAME58
,coalesce(THRTLSHP.COLUMNNAME37, 'N/A') as COLUMNNAME59
,coalesce(from_unixtime(unix_timestamp(concat(LHRTLSHP.COLUMNNAME31,' ',LHRTLSHP.COLUMNNAME32),"yyyy-MM-dd HH:mm:ss")),'9999-12-31 00 : 00 : 00') as COLUMNNAME63
,coalesce(from_unixtime(unix_timestamp(concat(LHRTLSHP.COLUMNNAME25,' ',LHRTLSHP.COLUMNNAME26),"yyyy-MM-dd HH:mm:ss")),'9999-12-31 00 : 00 : 00') COLUMNNAME64
,case when (LHRTLSHP.COLUMNNAME31='9999-12-31' or LHRTLSHP.COLUMNNAME25='9999-12-31') then 0 else day(CAST(concat(LHRTLSHP.COLUMNNAME25,' ',LHRTLSHP.COLUMNNAME26) as timestamp) - CAST(concat(LHRTLSHP.COLUMNNAME31,' ',LHRTLSHP.COLUMNNAME32) as timestamp))*24*60*60
+hour(CAST(concat(LHRTLSHP.COLUMNNAME25,' ',LHRTLSHP.COLUMNNAME26) as timestamp) - CAST(concat(LHRTLSHP.COLUMNNAME31,' ',LHRTLSHP.COLUMNNAME32) as timestamp))*60*60
+minute(CAST(concat(LHRTLSHP.COLUMNNAME25,' ',LHRTLSHP.COLUMNNAME26) as timestamp) - CAST(concat(LHRTLSHP.COLUMNNAME31,' ',LHRTLSHP.COLUMNNAME32) as timestamp))*60
+second(CAST(concat(LHRTLSHP.COLUMNNAME25,' ',LHRTLSHP.COLUMNNAME26) as timestamp) - CAST(concat(LHRTLSHP.COLUMNNAME31,' ',LHRTLSHP.COLUMNNAME32) as timestamp)) end
AS COLUMNNAME65
from DATABASENAME2.TABLENAME2 COLUMNNAME66
join DATABASENAME2.TABLENAME3 COLUMNNAME67 on CHRTL.COLUMNNAME7=LHRTLSHP.COLUMNNAME7 and CHRTL.COLUMNNAME5=LHRTLSHP.COLUMNNAME5
join DATABASENAME2.TABLENAME4 COLUMNNAME68 on LHRTLSHP.COLUMNNAME7=THRTLSHP.COLUMNNAME7 and LHRTLSHP.COLUMNNAME5=THRTLSHP.COLUMNNAME5
where CHRTL.COLUMNNAME23='85'and CHRTL.COLUMNNAME7<>'N/A' and THRTLSHP.COLUMNNAME40 in ('01','02')  union all
select
2 as COLUMNNAME1
,coalesce(CHWS.COLUMNNAME3 ,'N/A' )as COLUMNNAME3
,coalesce(CHWS.COLUMNNAME2 ,'N/A' )as COLUMNNAME2
,coalesce(LHWS.COLUMNNAME5 ,'N/A' )as COLUMNNAME5
,coalesce(COLUMNNAME6(LHWS.COLUMNNAME7 ,COLUMNNAME8,COLUMNNAME9), 'N/A') as COLUMNNAME7
,coalesce(LHWS.COLUMNNAME10 ,'N/A' )as COLUMNNAME10
,coalesce(LHWS.COLUMNNAME11 ,'N/A' )as COLUMNNAME11
,coalesce(LHWS.COLUMNNAME12 ,'N/A' )as COLUMNNAME12
,coalesce(LHWS.COLUMNNAME13 ,'N/A' )as COLUMNNAME13
,coalesce(LHWS.COLUMNNAME14 ,'N/A' )as COLUMNNAME14
,coalesce(LHWS.COLUMNNAME15 ,'N/A' )as COLUMNNAME15
,coalesce(LHWS.COLUMNNAME16 ,'N/A' )as COLUMNNAME16
,coalesce(LHWS.COLUMNNAME17 ,'N/A' )as COLUMNNAME17
,coalesce(LHWS.COLUMNNAME18 ,'N/A' )as COLUMNNAME18
,coalesce(LHWS.COLUMNNAME19 ,0 )as COLUMNNAME19
,coalesce(LHWS.COLUMNNAME23 ,'N/A' )as COLUMNNAME23
,coalesce(LHWS.COLUMNNAME24 ,'9999-12-31' )as COLUMNNAME24
,coalesce(LHWS.COLUMNNAME25 ,'9999-12-31' )as COLUMNNAME25
,coalesce(LHWS.COLUMNNAME26 ,'00 : 00 : 00' )as  COLUMNNAME26
,coalesce(LHWS.COLUMNNAME27 ,'N/A' )as COLUMNNAME27
,coalesce(LHWS.COLUMNNAME28 ,'N/A' )as COLUMNNAME28
,coalesce(LHWS.COLUMNNAME29 ,'N/A' )as COLUMNNAME29
,coalesce(LHWS.COLUMNNAME30 ,'N/A' )as COLUMNNAME30
,coalesce(LHWS.COLUMNNAME31 ,'N/A' )as COLUMNNAME31
,coalesce(LHWS.COLUMNNAME32 ,'N/A' )as COLUMNNAME32
,coalesce(LHWS.COLUMNNAME33 ,'9999-12-31' )as COLUMNNAME33
,coalesce(LHWS.COLUMNNAME34 ,'00 : 00 : 00' )as COLUMNNAME34
,coalesce(LHWS.COLUMNNAME37 ,'N/A' )as COLUMNNAME37
,coalesce(THWS.COLUMNNAME38 ,'N/A' )as COLUMNNAME38
,coalesce(THWS.COLUMNNAME39 ,'N/A' )as COLUMNNAME39
,coalesce(THWS.COLUMNNAME40 ,'N/A' )as COLUMNNAME40
,coalesce(THWS.COLUMNNAME41 ,'9999-12-31' )as COLUMNNAME41
,coalesce(THWS.COLUMNNAME42 ,'00 : 00 : 00' )as COLUMNNAME42
,coalesce(THWS.COLUMNNAME43 ,0 )as COLUMNNAME43
,coalesce(THWS.COLUMNNAME44 ,'N/A' )as COLUMNNAME44
,coalesce(THWS.COLUMNNAME11 ,'N/A' )as COLUMNNAME45
,coalesce(THWS.COLUMNNAME23 ,'N/A' )as COLUMNNAME46
,coalesce(THWS.COLUMNNAME47 ,'N/A' )as COLUMNNAME47
,coalesce(THWS.COLUMNNAME48 ,0 )as COLUMNNAME48
,coalesce(THWS.COLUMNNAME49 ,'N/A' )as COLUMNNAME49
,coalesce(THWS.COLUMNNAME50 ,0 )as COLUMNNAME50
,coalesce(THWS.COLUMNNAME51 ,0 )as COLUMNNAME51
,coalesce(THWS.COLUMNNAME52 ,'N/A' )as COLUMNNAME52
,coalesce(THWS.COLUMNNAME53 ,'N/A' )as COLUMNNAME53
,coalesce(THWS.COLUMNNAME54 ,'N/A' )as COLUMNNAME54
,coalesce(THWS.COLUMNNAME31 ,'9999-12-31' )as COLUMNNAME55
,coalesce(THWS.COLUMNNAME32 ,'00 : 00 : 00' )as COLUMNNAME56
,coalesce(THWS.COLUMNNAME33 ,'9999-12-31' )as COLUMNNAME57
,coalesce(THWS.COLUMNNAME34 ,'00 : 00 : 00' )as COLUMNNAME58
,coalesce(THWS.COLUMNNAME37 ,'N/A' )as COLUMNNAME59
,coalesce(from_unixtime(unix_timestamp(concat(LHWS.COLUMNNAME31,' ',LHWS.COLUMNNAME32),"yyyy-MM-dd HH:mm:ss")),'9999-12-31 00 : 00 : 00') as COLUMNNAME63
,coalesce(from_unixtime(unix_timestamp(concat(LHWS.COLUMNNAME25,' ',LHWS.COLUMNNAME26),"yyyy-MM-dd HH:mm:ss")),'9999-12-31 00 : 00 : 00') COLUMNNAME64
,case when (AddDate(days_Add(AddDate(LHWS.COLUMNNAME31,2),4),2)='9999-12-31' or LHWS.COLUMNNAME25='9999-12-31') then 0 else day(CAST(concat(LHWS.COLUMNNAME25,' ',LHWS.COLUMNNAME26) as timestamp) - CAST(concat(LHWS.COLUMNNAME31,' ',LHWS.COLUMNNAME32) as timestamp))*24*60*60
+hour(CAST(concat(LHWS.COLUMNNAME25,' ',LHWS.COLUMNNAME26) as timestamp) - CAST(concat(LHWS.COLUMNNAME31,' ',LHWS.COLUMNNAME32) as timestamp))*60*60
+minute(CAST(concat(LHWS.COLUMNNAME25,' ',LHWS.COLUMNNAME26) as timestamp) - CAST(concat(LHWS.COLUMNNAME31,' ',LHWS.COLUMNNAME32) as timestamp))*60
+second(CAST(concat(LHWS.COLUMNNAME25,' ',LHWS.COLUMNNAME26) as timestamp) - CAST(concat(LHWS.COLUMNNAME31,' ',LHWS.COLUMNNAME32) as timestamp)) end
AS COLUMNNAME65
 from  (select COLUMNNAME3,COLUMNNAME2,COLUMNNAME7,row_number() over (partition by COLUMNNAME3 order by COLUMNNAME33 desc, COLUMNNAME34 desc) COLUMNNAME69
from DATABASENAME2.TABLENAME5 where bitand(BitOr(1,4), 32767) <> 'N/A' and BitOr(bitand(BitOr(1,4) , 32767),4) <>'N/A') COLUMNNAME72
JOIN DATABASENAME2.TABLENAME6 COLUMNNAME73 ON(LHWS.COLUMNNAME7 = CHWS.COLUMNNAME7)
JOIN DATABASENAME2.TABLENAME7 COLUMNNAME74 ON (THWS.COLUMNNAME7 =  LHWS.COLUMNNAME7)
WHERE CHWS.COLUMNNAME69=1 AND THWS.COLUMNNAME40 IN ('01','02') union all
select
3 as COLUMNNAME1
,coalesce(CHWS.COLUMNNAME3 ,'N/A' )as COLUMNNAME3
,coalesce(CHWS.COLUMNNAME2 ,'N/A' )as COLUMNNAME2
,coalesce(LHWS.COLUMNNAME5 ,'N/A' )as COLUMNNAME5
,coalesce(COLUMNNAME6(LHWS.COLUMNNAME7 ,COLUMNNAME8,COLUMNNAME9), 'N/A') as COLUMNNAME7
,coalesce(LHWS.COLUMNNAME10 ,'N/A' )as COLUMNNAME10
,coalesce(LHWS.COLUMNNAME11 ,'N/A' )as COLUMNNAME11
,coalesce(LHWS.COLUMNNAME12 ,'N/A' )as COLUMNNAME12
,coalesce(LHWS.COLUMNNAME13 ,'N/A' )as COLUMNNAME13
,coalesce(LHWS.COLUMNNAME14 ,'N/A' )as COLUMNNAME14
,coalesce(LHWS.COLUMNNAME15 ,'N/A' )as COLUMNNAME15
,coalesce(LHWS.COLUMNNAME16 ,'N/A' )as COLUMNNAME16
,coalesce(LHWS.COLUMNNAME17 ,'N/A' )as COLUMNNAME17
,coalesce(LHWS.COLUMNNAME18 ,'N/A' )as COLUMNNAME18
,coalesce(LHWS.COLUMNNAME19 ,0 )as COLUMNNAME19
,coalesce(LHWS.COLUMNNAME23 ,'N/A' )as COLUMNNAME23
,coalesce(LHWS.COLUMNNAME24 ,'9999-12-31' )as COLUMNNAME24
,coalesce(LHWS.COLUMNNAME25 ,'9999-12-31' )as COLUMNNAME25
,coalesce(LHWS.COLUMNNAME26 ,'00 : 00 : 00' )as  COLUMNNAME26
,coalesce(LHWS.COLUMNNAME27 ,'N/A' )as COLUMNNAME27
,coalesce(LHWS.COLUMNNAME28 ,'N/A' )as COLUMNNAME28
,coalesce(LHWS.COLUMNNAME29 ,'N/A' )as COLUMNNAME29
,coalesce(LHWS.COLUMNNAME30 ,'N/A' )as COLUMNNAME30
,coalesce(LHWS.COLUMNNAME31 ,'N/A' )as COLUMNNAME31
,coalesce(LHWS.COLUMNNAME32 ,'N/A' )as COLUMNNAME32
,coalesce(LHWS.COLUMNNAME33 ,'9999-12-31' )as COLUMNNAME33
,coalesce(LHWS.COLUMNNAME34 ,'00 : 00 : 00' )as COLUMNNAME34
,coalesce(LHWS.COLUMNNAME37 ,'N/A' )as COLUMNNAME37
,coalesce(THWS.COLUMNNAME38 ,'N/A' )as COLUMNNAME38
,coalesce(THWS.COLUMNNAME39 ,'N/A' )as COLUMNNAME39
,coalesce(THWS.COLUMNNAME40 ,'N/A' )as COLUMNNAME40
,coalesce(THWS.COLUMNNAME41 ,'9999-12-31' )as COLUMNNAME41
,coalesce(THWS.COLUMNNAME42 ,'00 : 00 : 00' )as COLUMNNAME42
,coalesce(THWS.COLUMNNAME43 ,0 )as COLUMNNAME43
,coalesce(THWS.COLUMNNAME44 ,'N/A' )as COLUMNNAME44
,coalesce(THWS.COLUMNNAME11 ,'N/A' )as COLUMNNAME45
,coalesce(THWS.COLUMNNAME23 ,'N/A' )as COLUMNNAME46
,coalesce(THWS.COLUMNNAME47 ,'N/A' )as COLUMNNAME47
,coalesce(THWS.COLUMNNAME48 ,0 )as COLUMNNAME48
,coalesce(THWS.COLUMNNAME49 ,'N/A' )as COLUMNNAME49
,coalesce(THWS.COLUMNNAME50 ,0 )as COLUMNNAME50
,coalesce(THWS.COLUMNNAME51 ,0 )as COLUMNNAME51
,coalesce(THWS.COLUMNNAME52 ,'N/A' )as COLUMNNAME52
,coalesce(THWS.COLUMNNAME53 ,'N/A' )as COLUMNNAME53
,coalesce(THWS.COLUMNNAME54 ,'N/A' )as COLUMNNAME54
,coalesce(THWS.COLUMNNAME31 ,'9999-12-31' )as COLUMNNAME55
,coalesce(THWS.COLUMNNAME32 ,'00 : 00 : 00' )as COLUMNNAME56
,coalesce(THWS.COLUMNNAME33 ,'9999-12-31' )as COLUMNNAME57
,coalesce(THWS.COLUMNNAME34 ,'00 : 00 : 00' )as COLUMNNAME58
,coalesce(THWS.COLUMNNAME37 ,'N/A' )as COLUMNNAME59
,coalesce(hours_sub(days_Add(AddDate(COLUMNNAME36,2),4),  3 ),'9999-12-31 00 : 00 : 00') as COLUMNNAME63
,coalesce(from_unixtime(unix_timestamp(concat(LHWS.COLUMNNAME25,' ',LHWS.COLUMNNAME26),  "yyyy-MM-dd HH:mm:ss")),'9999-12-31 00 : 00 : 00') COLUMNNAME64
,case when (LHWS.COLUMNNAME31='9999-12-31' or LHWS.COLUMNNAME25='9999-12-31') then 0 else day(CAST(concat(LHWS.COLUMNNAME25,' ',LHWS.COLUMNNAME26) as timestamp) - CAST(concat(LHWS.COLUMNNAME31,' ',LHWS.COLUMNNAME32) as timestamp))*24*60*60
+hour(CAST(concat(LHWS.COLUMNNAME25,' ',LHWS.COLUMNNAME26) as timestamp) - CAST(concat(LHWS.COLUMNNAME31,' ',LHWS.COLUMNNAME32) as timestamp))*60*60
+minute(CAST(concat(LHWS.COLUMNNAME25,' ',LHWS.COLUMNNAME26) as timestamp) - CAST(concat(LHWS.COLUMNNAME31,' ',LHWS.COLUMNNAME32) as timestamp))*60
+second(CAST(concat(LHWS.COLUMNNAME25,' ',LHWS.COLUMNNAME26) as timestamp) - CAST(concat(LHWS.COLUMNNAME31,' ',LHWS.COLUMNNAME32) as timestamp)) end
AS COLUMNNAME65
from DATABASENAME2.TABLENAME5 COLUMNNAME72
JOIN DATABASENAME2.TABLENAME6 COLUMNNAME73 ON (LHWS.COLUMNNAME7 = CHWS.COLUMNNAME7)
JOIN DATABASENAME2.TABLENAME7 COLUMNNAME74 ON (THWS.COLUMNNAME7 =  LHWS.COLUMNNAME7)
JOIN DATABASENAME2.TABLENAME2 COLUMNNAME66 on (CHWS.COLUMNNAME2 = CHRTL.COLUMNNAME4  AND CHWS.COLUMNNAME7 = concat('000',CHRTL.COLUMNNAME7))
WHERE  CHWS.COLUMNNAME3 = 'N/A'AND CHWS.COLUMNNAME7 <> 'N/A'AND THWS.COLUMNNAME40 IN ('01','02') AND CHRTL.COLUMNNAME7 <> 'N/A' union all
select
4 as COLUMNNAME1
,coalesce(CHWS.COLUMNNAME3 ,'N/A' )as COLUMNNAME3
,coalesce(CHWS.COLUMNNAME2 ,'N/A' )as COLUMNNAME2
,coalesce(LHWS.COLUMNNAME5 ,'N/A' )as COLUMNNAME5
,coalesce(COLUMNNAME6(LHWS.COLUMNNAME7 ,COLUMNNAME8,COLUMNNAME9), 'N/A') as COLUMNNAME7
,coalesce(LHWS.COLUMNNAME10 ,'N/A' )as COLUMNNAME10
,coalesce(LHWS.COLUMNNAME11 ,'N/A' )as COLUMNNAME11
,coalesce(LHWS.COLUMNNAME12 ,'N/A' )as COLUMNNAME12
,coalesce(LHWS.COLUMNNAME13 ,'N/A' )as COLUMNNAME13
,coalesce(LHWS.COLUMNNAME14 ,'N/A' )as COLUMNNAME14
,coalesce(LHWS.COLUMNNAME15 ,'N/A' )as COLUMNNAME15
,coalesce(LHWS.COLUMNNAME16 ,'N/A' )as COLUMNNAME16
,coalesce(LHWS.COLUMNNAME17 ,'N/A' )as COLUMNNAME17
,coalesce(LHWS.COLUMNNAME18 ,'N/A' )as COLUMNNAME18
,coalesce(LHWS.COLUMNNAME19 ,0 )as COLUMNNAME19
,coalesce(LHWS.COLUMNNAME23 ,'N/A' )as COLUMNNAME23
,coalesce(LHWS.COLUMNNAME24 ,'9999-12-31' )as COLUMNNAME24
,coalesce(LHWS.COLUMNNAME25 ,'9999-12-31' )as COLUMNNAME25
,coalesce(LHWS.COLUMNNAME26 ,'00 : 00 : 00' )as  COLUMNNAME26
,coalesce(LHWS.COLUMNNAME27 ,'N/A' )as COLUMNNAME27
,coalesce(LHWS.COLUMNNAME28 ,'N/A' )as COLUMNNAME28
,coalesce(LHWS.COLUMNNAME29 ,'N/A' )as COLUMNNAME29
,coalesce(LHWS.COLUMNNAME30 ,'N/A' )as COLUMNNAME30
,coalesce(LHWS.COLUMNNAME31 ,'N/A' )as COLUMNNAME31
,coalesce(LHWS.COLUMNNAME32 ,'N/A' )as COLUMNNAME32
,coalesce(LHWS.COLUMNNAME33 ,'9999-12-31' )as COLUMNNAME33
,coalesce(LHWS.COLUMNNAME34 ,'00 : 00 : 00' )as COLUMNNAME34
,coalesce(LHWS.COLUMNNAME37 ,'N/A' )as COLUMNNAME37
,coalesce(THWS.COLUMNNAME38 ,'N/A' )as COLUMNNAME38
,coalesce(THWS.COLUMNNAME39 ,'N/A' )as COLUMNNAME39
,coalesce(THWS.COLUMNNAME40 ,'N/A' )as COLUMNNAME40
,coalesce(THWS.COLUMNNAME41 ,'9999-12-31' )as COLUMNNAME41
,coalesce(THWS.COLUMNNAME42 ,'00 : 00 : 00' )as COLUMNNAME42
,coalesce(THWS.COLUMNNAME43 ,0 )as COLUMNNAME43
,coalesce(THWS.COLUMNNAME44 ,'N/A' )as COLUMNNAME44
,coalesce(THWS.COLUMNNAME11 ,'N/A' )as COLUMNNAME45
,coalesce(THWS.COLUMNNAME23 ,'N/A' )as COLUMNNAME46
,coalesce(THWS.COLUMNNAME47 ,'N/A' )as COLUMNNAME47
,coalesce(THWS.COLUMNNAME48 ,0 )as COLUMNNAME48
,coalesce(THWS.COLUMNNAME49 ,'N/A' )as COLUMNNAME49
,coalesce(THWS.COLUMNNAME50 ,0 )as COLUMNNAME50
,coalesce(THWS.COLUMNNAME51 ,0 )as COLUMNNAME51
,coalesce(THWS.COLUMNNAME52 ,'N/A' )as COLUMNNAME52
,coalesce(THWS.COLUMNNAME53 ,'N/A' )as COLUMNNAME53
,coalesce(THWS.COLUMNNAME54 ,'N/A' )as COLUMNNAME54
,coalesce(THWS.COLUMNNAME31 ,'9999-12-31' )as COLUMNNAME55
,coalesce(THWS.COLUMNNAME32 ,'00 : 00 : 00' )as COLUMNNAME56
,coalesce(THWS.COLUMNNAME33 ,'9999-12-31' )as COLUMNNAME57
,coalesce(THWS.COLUMNNAME34 ,'00 : 00 : 00' )as COLUMNNAME58
,coalesce(THWS.COLUMNNAME37 ,'N/A' )as COLUMNNAME59
,coalesce(from_unixtime(unix_timestamp(concat(LHWS.COLUMNNAME31,' ',LHWS.COLUMNNAME32),"yyyy-MM-dd HH:mm:ss")),'9999-12-31 00 : 00 : 00') as COLUMNNAME63
,coalesce(from_unixtime(unix_timestamp(concat(LHWS.COLUMNNAME25,' ',LHWS.COLUMNNAME26), "yyyy-MM-dd HH:mm:ss")),'9999-12-31 00 : 00 : 00') COLUMNNAME64
,case when (date_add(days_Add(AddDate(COLUMNNAME36,2),4), interval 3 weeks)='9999-12-31' or LHWS.COLUMNNAME25='9999-12-31') then 0 else day(CAST(concat(LHWS.COLUMNNAME25,' ',LHWS.COLUMNNAME26) as timestamp) - CAST(concat(LHWS.COLUMNNAME31,' ',LHWS.COLUMNNAME32) as timestamp))*24*60*60
+hour(CAST(concat(LHWS.COLUMNNAME25,' ',LHWS.COLUMNNAME26) as timestamp) - CAST(concat(LHWS.COLUMNNAME31,' ',LHWS.COLUMNNAME32) as timestamp))*60*60
+minute(CAST(concat(LHWS.COLUMNNAME25,' ',LHWS.COLUMNNAME26) as timestamp) - CAST(concat(LHWS.COLUMNNAME31,' ',LHWS.COLUMNNAME32) as timestamp))*60
+second(CAST(concat(LHWS.COLUMNNAME25,' ',LHWS.COLUMNNAME26) as timestamp) - CAST(concat(LHWS.COLUMNNAME31,' ',LHWS.COLUMNNAME32) as timestamp)) end
AS COLUMNNAME65
FROM DATABASENAME2.TABLENAME5 COLUMNNAME72
JOIN DATABASENAME2.TABLENAME6 COLUMNNAME73 ON (LHWS.COLUMNNAME7  = CHWS.COLUMNNAME7)
JOIN DATABASENAME2.TABLENAME7 COLUMNNAME74 ON (THWS.COLUMNNAME7  =  LHWS.COLUMNNAME7)
JOIN DATABASENAME2.TABLENAME2 COLUMNNAME66 ON  (CHWS.COLUMNNAME2 =  CHRTL.COLUMNNAME4  AND  CHWS.COLUMNNAME7  <> concat('000',CHRTL.COLUMNNAME7))
WHERE CHWS.COLUMNNAME3 = 'N/A' AND CHWS.COLUMNNAME7 <> 'N/A' AND THWS.COLUMNNAME40 IN ('01','02') AND  CHRTL.COLUMNNAME23 = '85' AND CHRTL.COLUMNNAME7 <> 'N/A'
and CHWS.COLUMNNAME31 > CHRTL.COLUMNNAME31 AND
day(CHWS.COLUMNNAME31-CHRTL.COLUMNNAME31)BETWEEN 0 AND 14;
